<a href="https://colab.research.google.com/github/Ralein/AI-ML/blob/colab/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas as py

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as

In [ ]:
import pandas as pd
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
import pandas as pd
df = pd.read_json("/content/sample_data/anscombe.json")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Series  44 non-null     object
 1   X       44 non-null     int64
 2   Y       44 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ KB

In [ ]:
import pandas as pd

df = pd.read_csv("/content/sample_data/README.md", sep="|", engine="python")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 1 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   This directory includes a few sample datasets to get you started.  13 non-null     object
dtypes: object(1)
memory usage: 236.0+ bytes
None

niche
data description
Feature description
Analysis question
data type checking
handling null values
duplicate values
Duplicate  unique featurs
data standardize
Inconsistent value

#int, float, object (astype)

column_name=column_name.astype("new data)

#datetime
pd.to_datetime()

In [ ]:
df["longitude"]=df["longitude"].astype("int")
df["latitude"]=df["latitude"].astype("int")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114,34,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114,34,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114,33,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114,33,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114,33,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124,40,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124,40,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124,41,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124,41,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124,40,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

#handling null value
column_name.isnull().sum()

.sum() is used to find total

#find % of missing

In [ ]:
df.isnull()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
16995,False,False,False,False,False,False,False,False,False
16996,False,False,False,False,False,False,False,False,False
16997,False,False,False,False,False,False,False,False,False
16998,False,False,False,False,False,False,False,False,False
16999,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64


#numerical
mean,median, mode, manual

#catagorical
mode, manual

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/FINAL_DATASET.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6557 entries, 0 to 6556
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   image_id              6557 non-null   int64
 1   image_url             6557 non-null   object
 2   label                 6557 non-null   object
 3   label_numeric         6557 non-null   int64
 4   category              6557 non-null   object
 5   gender                6557 non-null   object
 6   age_group             6557 non-null   object
 7   source                6557 non-null   object
 8   fake_method           3767 non-null   object
 9   image_quality         6557 non-null   object
 10  resolution            6557 non-null   object
 11  confidence_score      6557 non-null   float64
 12  detection_difficulty  6557 non-null   object
 13  dataset_split         6557 non-null   object
 14  date_collected        6557 non-null   object
 15  version               6557 non-null   object
 16  year                  6557 non-null   int64
dtypes: float64(1), int64(3), object(13)
memory usage: 871.0+ KB

In [ ]:
df.isnull()

,image_id,image_url,label,label_numeric,category,gender,age_group,source,fake_method,image_quality,resolution,confidence_score,detection_difficulty,dataset_split,date_collected,version,year
0,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6552,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6553,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6554,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6555,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6556,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

image_id                   0
image_url                  0
label                      0
label_numeric              0
category                   0
gender                     0
age_group                  0
source                     0
fake_method             2790
image_quality              0
resolution                 0
confidence_score           0
detection_difficulty       0
dataset_split              0
date_collected             0
version                    0
year                       0
dtype: int64

In [ ]:
df['date_collected'] = pd.to_datetime(df['date_collected'])

In [ ]:
df['year'] = pd.to_datetime(df['year'], format='%Y')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6557 entries, 0 to 6556
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   image_id              6557 non-null   int64
 1   image_url             6557 non-null   object
 2   label                 6557 non-null   object
 3   label_numeric         6557 non-null   int64
 4   category              6557 non-null   object
 5   gender                6557 non-null   object
 6   age_group             6557 non-null   object
 7   source                6557 non-null   object
 8   fake_method           3767 non-null   object
 9   image_quality         6557 non-null   object
 10  resolution            6557 non-null   object
 11  confidence_score      6557 non-null   float64
 12  detection_difficulty  6557 non-null   object
 13  dataset_split         6557 non-null   object
 14  date_collected        6557 non-null   datetime64[ns]
 15  version               6557 non-null   object
 16  year                  6557 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2), object(12)
memory usage: 871.0+ KB

In [ ]:
print(df.columns)

Index(['image_id', 'image_url', 'label', 'label_numeric', 'category', 'gender',
       'age_group', 'source', 'fake_method', 'image_quality', 'resolution',
       'confidence_score', 'detection_difficulty', 'dataset_split',
       'date_collected', 'version', 'year'],
      dtype='object')

In [ ]:
print(df.dtypes)

image_id                         int64
image_url                       object
label                           object
label_numeric                    int64
category                        object
gender                          object
age_group                       object
source                          object
fake_method                     object
image_quality                   object
resolution                      object
confidence_score               float64
detection_difficulty            object
dataset_split                   object
date_collected          datetime64[ns]
version                         object
year                    datetime64[ns]
dtype: object

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6557 entries, 0 to 6556
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   image_id              6557 non-null   int64
 1   image_url             6557 non-null   object
 2   label                 6557 non-null   object
 3   label_numeric         6557 non-null   int64
 4   category              6557 non-null   object
 5   gender                6557 non-null   object
 6   age_group             6557 non-null   object
 7   source                6557 non-null   object
 8   fake_method           3767 non-null   object
 9   image_quality         6557 non-null   object
 10  resolution            6557 non-null   object
 11  confidence_score      6557 non-null   float64
 12  detection_difficulty  6557 non-null   object
 13  dataset_split         6557 non-null   object
 14  date_collected        6557 non-null   datetime64[ns]
 15  version               6557 non-null   object
 16  year                  6557 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2), object(12)
memory usage: 871.0+ KB

,image_id,label_numeric,confidence_score,date_collected,year
count,6557.00000,6557.000000,6557.000000,6557,6557
mean,3279.00000,0.425499,0.903741,2026-03-01 14:02:39.219155456,2025-12-31 23:59:59.999999744
min,1.00000,0.000000,0.800000,2026-01-01 00:00:00,2026-01-01 00:00:00
25%,1640.00000,0.000000,0.860000,2026-01-29 00:00:00,2026-01-01 00:00:00
50%,3279.00000,0.000000,0.910000,2026-03-02 00:00:00,2026-01-01 00:00:00
75%,4918.00000,1.000000,0.950000,2026-04-02 00:00:00,2026-01-01 00:00:00
max,6557.00000,1.000000,0.990000,2026-05-01 00:00:00,2026-01-01 00:00:00
std,1892.98719,0.494456,0.049982,NaN,NaN

In [ ]:
df['category'].unique()
df['gender'].unique()
df['fake_method'].unique()

array([nan, 'StyleGAN3'], dtype=object)

In [ ]:
df['category'].value_counts()
df['fake_method'].value_counts()

fake_method
StyleGAN3    3767
Name: count, dtype: int64

In [ ]:
df.groupby('category')['label_numeric'].mean()

category
AI Generated    0.0
Authentic       1.0
Name: label_numeric, dtype: float64