<a href="https://colab.research.google.com/github/Ralein/AI-ML/blob/colab/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#pandas - panel data; data manipulation ; data analysis
#numpy - numerical python
# 2 types of data; 1. series 2. Dataframe

In [ ]:
import pandas as pd
#one dimensional

s = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
a = pd.Series([4,6,7,5,3])
print(s)
print(a)

a    1
b    2
c    3
d    4
e    5
dtype: int64
0    4
1    6
2    7
3    5
4    3
dtype: int64

In [ ]:
s.values
s.index
s.size
s.reshape

In [ ]:
type(a)

pandas.core.series.Series

In [ ]:
#two dimensional - Dataframe
import numpy as np
z = np.arange(0,20).reshape(5,4)
df = pd.DataFrame(z, index = ['Row1','Row2','Row3','Row4','Row5'], columns = ['Col1','Col2','Col3','Col4'])

print(df)
display(df)

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [ ]:
data = pd.read_csv("/content/sample_data/Gaming_Academic_Performance.csv")
display(data)

,student_id,age,gender,gaming_hours,study_hours,sleep_hours,attendance,gaming_genre,social_activity,device_usage,reaction_time_ms,addiction_score,stress_level,grades
0,1,22,Male,7.23,8.78,6.96,91.44,FPS,3.25,9.36,235.84,14.69,Low,86.459555
1,2,19,Male,0.07,8.72,7.63,63.63,Casual,1.02,3.21,328.71,2.47,Medium,98.230000
2,3,23,Female,1.73,9.56,4.40,83.26,Casual,3.46,5.56,313.61,4.73,High,90.560000
3,4,20,Female,6.62,1.68,7.83,75.04,RPG,1.46,11.78,241.84,14.54,Low,32.670000
4,5,22,Female,5.36,5.83,5.55,65.57,FPS,1.01,8.23,249.31,12.48,Low,58.710000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,24,Male,6.33,5.09,4.83,63.74,FPS,4.11,9.96,231.33,11.14,Low,35.110000
7996,7997,22,Female,5.77,6.09,6.23,84.37,FPS,3.42,11.19,254.13,10.66,Low,60.800000
7997,7998,20,Male,2.87,8.51,8.62,67.30,FPS,2.36,6.40,305.00,6.42,Medium,90.280000
7998,7999,22,Female,0.98,2.99,7.29,61.13,FPS,2.02,4.57,325.36,2.14,Medium,56.330000
7999,8000,18,Female,1.73,8.75,7.65,78.68,RPG,4.03,6.33,302.25,4.05,Medium,100.000000

In [ ]:
import pandas as pd

data1 = pd.read_json("/content/sample_data/US_STATE_recipes.json")
display(data1)

,0,1,2,3,4,5,6,7,8,9,...,3753,3754,3755,3756,3757,3758,3759,3760,3761,3762
Contient,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,...,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa
Country_State,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
cuisine,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,...,Montana,Montana,Montana,Montana,Montana,Montana,Montana,Montana,Montana,Montana
title,Ground Beef and Cabbage,Old Fashioned Peach Cobbler,St. Louis Toasted Ravioli,Amish Friendship Bread Starter,Simple Fried Morel Mushrooms,Big Al's K.C. Bar-B-Q Sauce,Lemon Zucchini Bread,Springfield Style Cashew Chicken I,Kansas City Ice Water,St. Louis Pork Steaks,...,The Humble Shepherd,Easy Slow Cooker Venison Stew,Fennel in Wine and Honey,Spinach and Goat Cheese Salad with Beetroot Vi...,Montana Russian Black Bread,Cracked Black Venison,Montana Spicy Bison Dip,Grandpa Mack's Fifth-Generation Pancake Recipe,Couscous with Dried Cherries,Jo's Mountain Mush
URL,https://www.allrecipes.com/recipe/229324/groun...,https://www.allrecipes.com/recipe/19897/old-fa...,https://www.allrecipes.com/recipe/16907/st-lou...,https://www.allrecipes.com/recipe/7063/amish-f...,https://www.allrecipes.com/recipe/220833/simpl...,https://www.allrecipes.com/recipe/44491/big-al...,https://www.allrecipes.com/recipe/58817/lemon-...,https://www.allrecipes.com/recipe/9009/springf...,https://www.allrecipes.com/recipe/51923/kansas...,https://www.allrecipes.com/recipe/73669/st-lou...,...,https://www.allrecipes.com/recipe/76519/the-hu...,https://www.allrecipes.com/recipe/32081/easy-s...,https://www.allrecipes.com/recipe/95546/fennel...,https://www.allrecipes.com/recipe/46492/spinac...,https://www.allrecipes.com/recipe/236547/monta...,https://www.allrecipes.com/recipe/18774/cracke...,https://www.allrecipes.com/recipe/256810/monta...,https://www.allrecipes.com/recipe/279565/grand...,https://www.allrecipes.com/recipe/18273/cousco...,https://www.allrecipes.com/recipe/21272/jos-mo...
rating,4.5,4.6,4.5,4.7,4.7,4.8,4.6,4.4,4.5,4.0,...,4.4,4.5,4.1,4.7,4.0,4.4,4.3,3.7,4.2,4.3
total_time,60,130,25,14440,30,35,60,35,2,35,...,80,490,60,30,215,70,25,25,20,25
prep_time,15,30,15,30,20,15,15,15,2,10,...,30,10,15,25,20,10,10,5,5,10
cook_time,45,70,10,None,10,20,45,20,None,25,...,50,480,45,5,45,60,15,20,10,15
description,This ground beef and cabbage recipe combines l...,This old-fashioned peach cobbler recipe featur...,Toasted ravioli traces its roots to St. Louis....,Amish friendship bread starter is made with ye...,"The rich, meaty flavor of fresh morel mushroom...",This is a Kansas City-style BBQ sauce recipe s...,Lemon zest adds a touch of summer to this swee...,Fried chicken is topped with an Asian-style mi...,Citrus flavors are blended with gin and vodka....,Grilled pork steaks are juicy and tender in th...,...,A twist on the original shepherd's pie using g...,An easy slow cooker stew made with venison and...,"A great side dish for fennel lovers, originall...",A beet vinaigrette is drizzled over baby spina...,"Black bread, made with dark beer, coffee, mola...","Tasty and spicy, this is a simple venison stea...",Kick off game day with this touchdown-worthy M...,This family-favorite pancake recipe has been s...,My family loves couscous and this fruity varia...,"A jumbled, filling breakfast created when I wa..."
ingredients,"[1 large head cabbage, finely chopped, 1 (14.5...","[2.5 cups all-purpose flour, 4 tablespoons whi...","[1 (16 ounce) jar marinara sauce, 1 large egg,...","[1 (.25 ounce) package active dry yeast, 0.25 ...",[1 pound fresh morel mushrooms - dirt gently b...,"[2 cups ketchup, 2 cups tomato sauce, 1.25 cup...","[1.5 cups shredded zucchini, 0.75 cup white su...","[4 skinless, boneless chicken breasts, 2 cups ...","[1 fluid ounce gin, 1 fluid ounce vodka, 0.5 f...","[5 pork shoulder steaks, 0.125 teaspoon season...",...,"[cooking spray, 1.5 pounds russet potatoes, pe...","[2 pounds venison stew meat, 1 (10.75 ounce) c...","[4 fennel bulbs, trimmed and quartered, 0.25 c...","[1 cup walnuts, coarsely chopped, 2 tablespoon...","[2.5 cups whole wheat bread flour, 1 cup rye f...","[2 (1/2 pound) venison steaks, 2 teaspoons cra...","[1 pound ground bison, 0.5 cup chopped onion, ...","[2 cups all-purpose flour, 2 tablespoons white...","[1 cup chicken broth, 0.25 cup water, 0.25 cup...","[8 beef frankfurters, 3 red potatoes, cubed, 2..."
instructions,"[Place cabbage, tomatoes with juice, onion, It...","[Make crust: Sift together flour, 3 tablespoon...",[Heat marinara sauce in a saucepan over medium...,[Dissolve yeast in warm water in a small bowl;...,[Place halved morel mushrooms in a large bowl;...,"[Mix together ketchup, tomato sauce, brown sug...",[Preheat oven to 325 degrees F (165 degrees C)...,[Cut the chicken breasts into 1 inch pieces. I...,"[Combine the gin, vodka, lime juice, and tripl...",[Preheat an outdoor grill for medium-low heat ...,...,[Preheat an oven to 350 degrees F (175 degrees...,"[In a slow cooker, combine venison, cream of m...",[Place the fennel quarters in large deep skill...,"[In small saucepan over medium heat, cook and ...","[Place whole wheat bread flour, rye flour, coc...",[Season venison steaks with pepper and salt. M...,[Brown meat and onion in large skillet on medi...,"[Mix flour, sugar, baking powder, and salt tog...","[In a 2 quart saucepan, combine chicken broth,...",[Coat a large skillet with non-stick cooking s...
nutrients,"{'calories': '228 kcal', 'carbohydrateContent'...","{'calories': '338 kcal', 'carbohydrateContent'...","{'calories': '374 kcal', 'carbohydrateContent'...","{'calories': '34 kcal', 'carbohydrateContent':...","{'calories': '185 kcal', 'carbohydrateContent'...","{'calories': '46 kcal', 'carbohydrateContent':...","{'calories': '195 kcal', 'carbohydrateContent'...","{'calories': '652 kcal', 'carbohydrateContent'...",{},"{'calories': '517 kcal', 'carbohydrateContent'...",...,"{'calories': '567 kcal', 'carbohydrateContent'...","{'calories': '278 kcal', 'carbohydrateContent'...","{'calories': '133 kcal', 'carbohydrateContent'...","{'calories': '163 kcal', 'carbohydrateContent'...","{'calories': '241 kcal', 'carbohydrateContent'...","{'calories': '151 kcal', 'carbohydrateContent'...","{'calories': '98 kcal', 'carbohydrateContent':...","{'calories': '241 kcal', 'carbohydrateContent'...","{'calories': '243 kcal', 'carbohydrateContent'...","{'calories': '460 kcal', 'carbohydrateContent'..."
serves,6 servings,18 servings,6 servings,120 servings,4 servings,48 servings,12 servings,6 servings,1 serving,5 servings,...,6 servings,6 servings,8 servings,12 servings,10 servings,4 servings,20 servings,9 servings,4 servings,6 servings

In [ ]:
data2 = pd.read_csv("/content/sample_data/README.md", sep="|", engine="python")
print(data2)

   This directory includes a few sample datasets to get you started.
0   *   `california_housing_data*.csv` is Californ...
1           Census; more information is available at:
2       https://docs.google.com/document/d/e/2PACX...
3          *   `mnist_*.csv` is a small sample of the
4       [MNIST database](https://en.wikipedia.org/...
5       described at: http://yann.lecun.com/exdb/m...
6              *   `anscombe.json` contains a copy of
7       [Anscombe's quartet](https://en.wikipedia....
8                         was originally described in
9       Anscombe, F. J. (1973). 'Graphs in Statist...
10        Statistician. 27 (1): 17-21. JSTOR 2682899.
11                   and our copy was prepared by the
12      [vega_datasets library](https://github.com...

In [ ]:
data3 = pd.read_csv("/content/sample_students.xml")
print(data3)

             <?xml version="1.0" encoding="UTF-8"?>
0                                        <students>
1                                         <student>
2                                      <id>101</id>
3                           <name>Ravi Kumar</name>
4                                     <age>21</age>
5                 <course>Computer Science</course>
6                                  <grade>A</grade>
7                                        </student>
8                                         <student>
9                                      <id>102</id>
10                       <name>Anjali Sharma</name>
11                                    <age>22</age>
12          <course>Information Technology</course>
13                                <grade>B+</grade>
14                                       </student>
15                                        <student>
16                                     <id>103</id>
17                         <name>Arjun Mehta</name>
18                                    <age>20</age>
19                     <course>Electronics</course>
20                                <grade>A-</grade>
21                                       </student>
22                                      </students>

In [3]:
import pandas as pd
mnist = pd.read_csv("/content/sample_data/mnist_train_small.csv")
print(mnist)

       6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...
19994  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
19996  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
19997  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
19998  5  0    0    0    0    0    0    0    0    0  ...      0      0      0

       0.584  0.585  0.586  0.587  0.588  0.589  0.590
0          0      0      0      0      0      0      0
1          0      0      0      0      0      0      0
2          0      0      0      0      0      0      0
3          0      0      0      0      0      0      0
4          0      0      0      0      0      0      0
...      ...    ...    ...    ...    ...    ...    ...
19994      0      0      0      0      0      0      0
19995      0      0      0      0      0      0      0
19996      0      0      0      0      0      0      0
19997      0      0      0      0      0      0      0
19998      0      0      0      0      0      0      0

[19999 rows x 785 columns]

In [4]:
mnist.head()

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
mnist.tail()

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
#single column - df name["col name"]
mnist["0"]

0        0
1        0
2        0
3        0
4        0
        ..
19994    0
19995    0
19996    0
19997    0
19998    0
Name: 0, Length: 19999, dtype: int64

In [10]:
mnist[["0","0.1"]]
#multi df

       0  0.1
0      0    0
1      0    0
2      0    0
3      0    0
4      0    0
...   ..  ...
19994  0    0
19995  0    0
19996  0    0
19997  0    0
19998  0    0

[19999 rows x 2 columns]

In [12]:
#select rows df.loc[index_value]
mnist.loc[0]

6        5
0        0
0.1      0
0.2      0
0.3      0
        ..
0.586    0
0.587    0
0.588    0
0.589    0
0.590    0
Name: 0, Length: 785, dtype: int64

In [19]:
#selecting multiple rows df_name.iloc(start:end)
mnist.iloc[19000:19996]

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
19000,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19001,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19002,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19003,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19004,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19991,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19992,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
#add a new column df_name["new col"] = operation
mnist["add"]=mnist["0"]+mnist["0.6"]
display(mnist)

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590,add
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
#Convert data; oldfile.to_excel("new_file_name")
mnist.to_excel("new_file_name.xlsx")

In [25]:
#remove columns

#df_name.drop([" "],axis=column/rows)
#axis - 0 ->rows(default)
#axix - 1 -> column
mnist.drop(["0.2"], axis=1)

,6,0,0.1,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590,add
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
mnist.drop(["1"])
display(mnist)

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590,add
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
#at update cell value
#data_frame.at[row,"col"]=new value

mnist.at[0,"6"] = 100
display(mnist)

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590,add
0,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
#filtering
#df_name[condition]
mnist[mnist["6"] == 2]
#important

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590,add
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19935,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19957,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19965,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19982,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0